# ВЕБИНАР 2: Основы Python часть 1
## Функциональное программирование на Python
Функциональное программирование — это парадигма программирования, в которой основным строительным блоком является функция. В Python функции являются объектами первого класса, что означает, что ими можно оперировать как и любыми другими объектами: присваивать переменным, передавать в другие функции, возвращать из функций и т.д.

Основные концепции функционального программирования в Python:

- Чистые функции: функции, которые не имеют побочных эффектов и всегда возвращают одно и то же значение при одинаковых входных данных.
- Лямбда-функции: анонимные функции, используемые для кратких одноразовых действий.
- Высшие функции: функции, принимающие другие функции в качестве аргументов или возвращающие функции.
- Замыкания: функции, которые сохраняют в своем контексте переменные из области видимости, в которой они были созданы.
- Рекурсия: функция, которая вызывает сама себя для решения подзадач.

## Функции
Функция в Python — это блок кода, который выполняется только тогда, когда он вызывается. Функции помогают разбивать программу на логические части, делают код более понятным и повторно используемым.
### Объявление функции

In [35]:
def имя_функции(параметры):
    """Строка документации функции"""
    # Тело функции
    return результат

In [36]:
def приветствие(name):
    """Функция для приветствия пользователя"""
    return f"Привет, {name}!"

# Вызов функции
print(приветствие("Алиса"))

Привет, Алиса!


## Аргументы функции

Функции могут принимать данные в виде параметров. Существует несколько типов аргументов в Python:

Позиционные аргументы: передаются в том порядке, в котором указаны параметры.
Именованные аргументы: передаются с указанием имени параметра.
Аргументы со значением по умолчанию: параметры, которым присвоено значение по умолчанию.
Неопределенное количество позиционных аргументов: *args.
Неопределенное количество именованных аргументов: **kwargs.

Примеры:

In [37]:
def информация(имя, возраст=18):
    print(f"Имя: {имя}")
    print(f"Возраст: {возраст}")

# Позиционные аргументы
информация("Боб", 25)

# Именованные аргументы
информация(возраст=30, имя="Ева")

# Использование значения по умолчанию
информация("Денис")

Имя: Боб
Возраст: 25
Имя: Ева
Возраст: 30
Имя: Денис
Возраст: 18


In [38]:
def add_number(list_nubers = []):
    list_nubers.append(1)
    print(list_nubers)

In [39]:
for _ in range(3):
    add_number()

add_number()

[1]
[1, 1]
[1, 1, 1]
[1, 1, 1, 1]


In [40]:
x = []

In [41]:
x

[]

In [42]:
y = []

In [43]:
x==y

True

In [44]:
id(x)

4696721856

In [45]:
id(y)

4583837312

In [52]:
def сумма(*числа):
    результат = 0
    for число in числа:
        результат += число
        print(результат)
    return результат

print(сумма(1, 2, 3, 4, 5, 8))

1
3
6
10
15
23
23


## Lambda-функции

Lambda-функции или анонимные функции — это небольшие одноразовые функции, которые определяются с помощью ключевого слова lambda.

Синтаксис:

lambda аргументы: выражение

Пример использования:

In [53]:
# Обычная функция
def удвоить(x):
    return x * 2

print(удвоить(5))

# Lambda-функция
удвоить_lambda = lambda x: x * 2
print(удвоить_lambda(5))

10
10


Lambda-функции часто используются вместе с функциями высшего порядка, такими как map(), filter() и sorted().

Пример с map():


In [54]:
числа = [1, 2, 3, 4, 5]
квадраты = list(map(lambda x: x ** 2, числа))
print(квадраты)

[1, 4, 9, 16, 25]


Генераторы

Генераторы — это функции, которые возвращают итератор и позволяют перебирать огромное количество значений без хранения их всех в памяти. Используют ключевое слово yield.

Пример генератора:

In [55]:
def счетчик(макс):
    n = 0
    while n < макс:
        yield n
        n += 1

for число in счетчик(5):
    print(число)

0
1
2
3
4


Генераторное выражение

Аналогично списковому включению, но создаёт генератор.

In [56]:
ген = (x ** 2 for x in range(5))
print(next(ген))  # 0
print(next(ген))  # 1
print(next(ген))  # 4

0
1
4


In [60]:
next(ген)

StopIteration: 

## Декораторы

Декораторы в Python — это функции, которые принимают другую функцию и расширяют ее функциональность без непосредственного изменения ее кода.

Создание декоратора

In [62]:
import time 

1728405938.96397

In [64]:
def декоратор(функция):
    def обертка(*args, **kwargs):
        print("До вызова функции")
        start = time.time()
        результат = функция(*args, **kwargs)
        print(time.time()-start)
        print("После вызова функции")
        return результат
    return обертка

@декоратор
def привет():
    print("Привет, мир!")

привет()

До вызова функции
Привет, мир!
6.198883056640625e-06
После вызова функции


## Логирование промежуточных вычислений

Логирование — процесс записи событий, которые происходят во время работы программы. В Python есть встроенный модуль logging для этого.

Пример использования logging:

In [65]:
import logging

# Настройка базового конфигурации логирования
logging.basicConfig(level=logging.INFO)

def вычисление(x, y):
    logging.info(f"Начало вычисления: x={x}, y={y}")
    результат = x + y
    logging.info(f"Результат вычисления: {результат}")
    return результат

вычисление(5, 10)

INFO:root:Начало вычисления: x=5, y=10
INFO:root:Результат вычисления: 15


15

## Библиотека NumPy, установка

NumPy — это фундаментальная библиотека для научных вычислений в Python. Она предоставляет высокопроизводительные многомерные массивы и различные функции для работы с ними.

Установка NumPy

В терминале или командной строке выполните:

pip install numpy


Создание массивов, многомерных массивов

NumPy предоставляет объект ndarray, который представляет собой многомерный массив фиксированного размера одного типа.

Импорт библиотеки

import numpy as np

Создание массива из списка

In [66]:
pip install numpy


[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [67]:
import numpy as np

In [68]:

a = np.array([1, 2, 3])
print(a)


[1 2 3]


In [69]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


## Доступ к элементам

Элементы массива можно получить с помощью индексов, как и в обычных списках Python.

Индексация


In [70]:
print(a[0])    # Первый элемент
print(b[1, 2]) # Элемент из второй строки, третий столбец

1
6


### Срезы

In [71]:
print(a[0:2])      # Элементы с 0 по 1
print(b[:, 1])     # Все строки, второй столбец

[1 2]
[2 5]


## Создание специальных массивов

NumPy предоставляет функции для создания массивов с определенными свойствами.

Нули и единицы

In [72]:
zeros = np.zeros((2, 3))
ones = np.ones((3, 2))
print("Нули:\n", zeros)
print("Единицы:\n", ones)

Нули:
 [[0. 0. 0.]
 [0. 0. 0.]]
Единицы:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [73]:
ones = np.ones((3, 2, 4))

In [74]:
ones

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [20]:
eye = np.eye(3)
print("Единичная матрица:\n", eye)

Единичная матрица:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Случайные числа

In [21]:
rand = np.random.random((2,2))
print("Случайные числа:\n", rand)

Случайные числа:
 [[0.14022566 0.56549164]
 [0.01544196 0.10790013]]


## Математические операции

NumPy позволяет выполнять поэлементные математические операции над массивами.

### Примеры операций

In [22]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

# Сложение
print("Сложение:\n", x + y)

# Вычитание
print("Вычитание:\n", x - y)

# Умножение поэлементное
print("Умножение:\n", x * y)

# Деление
print("Деление:\n", x / y)

Сложение:
 [[ 6  8]
 [10 12]]
Вычитание:
 [[-4 -4]
 [-4 -4]]
Умножение:
 [[ 5 12]
 [21 32]]
Деление:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [23]:
print("Матричное произведение:\n", x.dot(y))

Матричное произведение:
 [[19 22]
 [43 50]]


## Статистические операции

NumPy имеет функции для вычисления основных статистических параметров.

### Примеры:

In [24]:
array = np.array([1, 2, 3, 4, 5])

print("Сумма:", np.sum(array))
print("Минимум:", np.min(array))
print("Максимум:", np.max(array))
print("Среднее:", np.mean(array))
print("Медиана:", np.median(array))
print("Стандартное отклонение:", np.std(array))

Сумма: 15
Минимум: 1
Максимум: 5
Среднее: 3.0
Медиана: 3.0
Стандартное отклонение: 1.4142135623730951


## Копирование и организация

### Копирование массивов


In [75]:
a = np.array([1, 2, 3])
b = a          # Ссылка на тот же массив
c = a.copy()   # Глубокая копия

a[0] = 10
print("a:", a)
print("b:", b)
print("c:", c)

a: [10  2  3]
b: [10  2  3]
c: [1 2 3]


### Изменение формы массива

In [26]:
array = np.arange(6)
print("Исходный массив:", array)

reshaped = array.reshape((2, 3))
print("Новая форма:\n", reshaped)

Исходный массив: [0 1 2 3 4 5]
Новая форма:
 [[0 1 2]
 [3 4 5]]


## Объединение массивов

In [76]:
# Конкатенация
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = np.concatenate((a, b))
print("Конкатенация:", c)

Конкатенация: [1 2 3 4 5 6]


In [28]:
#Объединение по вертикали и горизонтали
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

# Вертикально (добавление строки)
vstack = np.vstack((x, y))
print("Вертикальное объединение:\n", vstack)

# Горизонтально (добавление столбца)
hstack = np.hstack((x, y.T))
print("Горизонтальное объединение:\n", hstack)

Вертикальное объединение:
 [[1 2]
 [3 4]
 [5 6]]
Горизонтальное объединение:
 [[1 2 5]
 [3 4 6]]


## Перестановка осей и транспонирование

In [77]:
# Транспонирование массива

In [78]:
mat = np.array([[1, 2], [3, 4]])
transposed = mat.T
print("Исходный массив:\n", mat)
print("Транспонированный массив:\n", transposed)

Исходный массив:
 [[1 2]
 [3 4]]
Транспонированный массив:
 [[1 3]
 [2 4]]


In [80]:
#Перестановка осей с transpose()
arr = np.random.randn(2,3,4)
print("Исходная форма:", arr.shape)

# Перестановка осей
new_arr = arr.transpose((1,0,2))
print("Новая форма:", new_arr.shape)

Исходная форма: (2, 3, 4)
Новая форма: (3, 2, 4)


## Быстрые поэлементные операции

NumPy позволяет выполнять операции над массивами гораздо быстрее, чем это делается в обычных циклах Python.

Пример поэлементных операций

In [81]:
array = np.arange(1000000)

# Операция NumPy
%timeit array * 2

# Операция с помощью списка и цикла
list_array = list(range(1000000))
%timeit [x * 2 for x in list_array]

418 µs ± 15.5 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
16 ms ± 231 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


# Заключение

Мы рассмотрели основные принципы функционального программирования в Python, узнали о функциях, аргументах, лямбда-функциях, генераторах и декораторах. Также познакомились с библиотекой NumPy: научились создавать массивы, выполнять операции над ними и использовать различные функции для обработки данных.

Эти знания являются фундаментальными для дальнейшего изучения Python и применения его в различных областях, таких как анализ данных, машинное обучение и научные исследования.